<div class="ceo"> INFO </div>
<b>CEO:</b> Ana Jords – since Nov 2020 <br>
Acounts Management:</b> Geraldo Filho since 2008<br>
<b>Localization:</b> EUA, Califórnia e Brazil<br>
<b>Type:</b> Tecnologia, Educação e TV. <br>
<b>Founded:</b> January 2008, Maceió Brazil and USA Califórnia. <br>
<b>Founders:</b> Geraldo SW, Billy Ray Cyrus

<div class="ti">Products:</div>

Products: ChalkArtes (2016)
Smart Studies (2008), Smart Vídeos e Pictures (2013), Smart Docs (2013-2017 substituted by Onedrive), SmartDicas onlyPTBR (2011-2017)


<div class="ti">Slogans:</div>
<p>
<strong>
2015: Rio 2<br>
2014: Changing everything<br>
2013: Moving Out<br>
2012: Geting New Perspective<br>
2011:The upgrade - Aprimoramentos<br>
2010: O final – The final<br>
2009: Inovação - Innovation<br>
2008: Dê a volta por cima - Superação – Overcoming<br>
</strong>



<br>
<br>
<div class="ti">Diretor executivo: </div>
<br>Angelina Jolie Key peoples: Keanu Reeves, Billy Ray Cyrus, Zooey Deschanel e Angelina Jolie

É uma empresa de tecnologia e estudos fundada por Geraldo Filho e Billy Ray Cyrus em 2008. Foi fundada por Geraldo Filho no inicio era um programa de aprendizagem. Atualmente TheSmartupdate (2010-presete) antiga Guia de Estudos (2008-2009) inicialmente era um projeto de superação, resumindo se baseava em estudar apenas o necessário em outras palavras superar os problemas com estudos pois era a única coisa boa, prazerosa e de fácil acesso e que certamente seria essencial para o futuro . Este projeto conseguiu ir além dos seus objetivos provou que é possível associar jogos e estudos, mantendo uma boa nota.Os interessados em comprar o programaforam aumentando a cada versão o que foi preciso aumentar a produção para atender a demanda.

</p>
<p>
<div class="ti">Associados chaves:</div>
Muitas outras pessoas como artistas ou pessoas influentes gostaram da ideia e resolveram contribuir com o projeto. Diante disso Geraldo teve a ideia que “Bem se eles querem contribuir ok mas poderiam criar seus próprios projetos ou se associarem a nossa empresa, ai ele abriu as portas da empresa” e foi exatamente o que aconteceu um bom exemplo que podemos citar é a atriz e cineasta Angelina Jolie que associou a sua ideia de ajudar os refugiados como um projeto pela Smartupdate. Atualmente ela foi nomeada Embaixadora pela ONU e teve seu trabalho reconhecido. Nota: Confira a lista de associados na homepage do site.
<div class="ti">Chegada ao Brasil</div>
Não demorou muito e em 2009 a empresa criou uma sede no Brasil, como um empresa que oferecia programas de estudos e bolsas escolares. Muitas pessoas de associaram.
<div class="ti">Serviços:</div>
Todos os serviços oferecidos pela empresa e suas características podem ser acessados no site os planos são compostos de Free e premium, a adoção de planos foi assinada por Geraldo Filho em 2010, porém só depois de decretada a ordem a Co-executiva Angelina Jolie não gostou nada desse tipo de divisão, Geraldo Filho disse que era para as contribuições Premium ajudasse a melhorar os serviços de uma certa forma. Mas não era assim que Angelina via as coisas ela queria igualdade para todos nos serviços ofertados, já que seus alunos utilizavam os serviços de informática da empresa. Para acabar com esse discursão Geraldo Filho assinou um decreto que os usuários de Angelina teriam conta Premium, ela achou melhor mas ainda não concorda com essa divisão de usuário. Com o passar do tempo a Empresa criou novos serviços como Smart Storage, Series, Movies, Pictures e etc.
<div class="ti">Billy Ray Cyrus e seu cargo</div>
Apesar de ser o co-fundador da empresa se mantem a maior parte da tempo ausente, ele mesmo admite não ter muito tempo ou cabeça para os negócios, logo que em 2010 enfrentou um processo de divorcio com sua esposa. Nas reuniões Bill sempre enviada um representando ou as vezes sempre deixava Geraldo tomar as decisões, mas em 2012 segundo ele isso irá mudar pois colocará alguém no seu cargo, muitos rumores dizem que Angelina Jolie poderá ocupar o seu lugar o que seria muito justo pois depois que encontrou na empresa tem contribuído muito afirma um dos funcionários.
<div class="ti">Propagandas</div>
A smartupdate só começou a fazer propagandas oficialmente em 2010 tendo com garota a atriz Katrina Kaif. Em 2011 Megan Fox a substituiu, mas em 2012 Katrina voltou.

</p>
