<p>Stay <b>connected</b> </p>


<div class="ti">Fast News 2020:</div>
<br>


<div class="date">Dec 27, 2020, 4:25pm EST - By @geraldo</div>
<p>New smart release</p>
<p>RAM: 1.5GB vs 4GB
Storage: 32GB vs 128GB
Processor: quad-core vs Octa-core Snapdragon 845
Camera: 13MP vs 12MP
support: fast charge, NFC, Display 5.8, 
</p>

<div class="date">Dec 27, 2020, 4:25pm EST - By @geraldo</div>
<p>New SX is coming soon</p>

<div class="date">Dec 12, 2020, 3:52pm EST - By @geraldo</div>
<p>First invoice SmartInter is available</p>

<div class="date">Dec 10, 2020, 3:52pm EST - By @geraldo</div>
<p>ClaroFlex is now back 12GB (8+4) by R$ 19,99 first month</p>

<div class="date">Dec 3, 2020, 3:52pm EST - By @geraldo</div>
<p><b>SmartInter PIX and Cartão Virtual</b> is now working after reinstall app isafe can block it temporaly.</p>

<div class="date">Date: 28, Nov 2020 - By @geraldo</div>
<p>Cientes do error ao gerar cartão virtual SmartInter, até a próxima segunda-feira vamos corrigir esse erro, sorry for that</p>
<p>PIX Inter is back until tonight, por medida de segunraça ao reintalar o iSafe o mesmo demora 24 hroas para voltar a opera</p>

<div class="date">Nov 26, 2020 - By @geraldo</div>
<p>Introducing Smart Inter Credit Card,
Beta Test limit <b>R$ 100,00</b></p>
<img src="./img/smartinterj.jpg" width="300" height="180">
<p>É a aposta do Geraldo para ganhar confiabilidade com seu CPF e tem várias expectativas de conseguir um novo crédito. Ainda em fase beta será ilberado para poucas pessoas, a fim de resolver bugs e quando ficar 100% funcional até 10 de Dezembro todos poderão usar.
Inicialmente será liberado apenas <b>R$ 100 reais</b> de limite de crédito<p>

<img src="./img/limit100.jpg" width="300" height="250">

<div class="date">Nov 25, 2020 - By @geraldo</div>
<p>Ana Jords can be new president in Brazil 

Nome forte com o objetivo de organizar vários problemas na empresa, ela pode ser designada por Geraldo Filho para o cargo de presidente.</p>

<div class="date">Nov 25, 2020 - By @geraldo</div>
<p>A issue on Santander App Banking, please disable VPN</p>


<div class="date">Nov 24, 2020 - By @geraldo</div>
<p>Claro Flex is shutdown, now use Vivo VPN</p>